### ISSUE TITLE
Not clear how to handle required parameters

### ISSUE THREAD

**Issue by ibalashov** [backuity/clist#16]
Parsing gives error if default value is not given:

> java.lang.IllegalArgumentException: Incorrect argument 'foo': an optional argument that has neither type Option nor Boolean must have a default value

It is not immediately clear why required parameter must have a default value. Setting default value for a required parameter and then asserting `passed value != default value` looks like an awkward workaround.

Shouldn't the library say e.g. 'Missing required parameter' and optionally show help page instead of throwing this exception?

**Comment by backuitist** [comment]
The reasoning was that `opt` are optional. But I agree, a required option
sounds like an oxymoron! So we could instead see `opt` as an argument in
the form `--name=value`. It should always be required therefore making the
`required` attribute obsolete.

**Comment by ibalashov** [comment]
> The reasoning was that `opt` are optional.
Indeed. In this case the error does make sense.

> So we could instead see `opt` as an argument in
the form `--name=value`. It should always be required therefore making the
`required` attribute obsolete.

Is there already a 'required' attribute available, or you're thinking of a new feature? If the latter, what the best current workaround for required args?

**Comment by backuitist** [comment]
Sorry, I'm just reading through the code now and my previous comment isn't quite right. There is a `required` attribute but for `arg[T]`, which is true by default. This feature isn't documented as it requires a bit of polishing. The documentation needs also a little clean-up regarding the differences between `arg` and `opt`.

Back to your initial problem, this runtime exception is something that ultimately should be a compilation error. This couldn't be done due to https://issues.scala-lang.org/browse/SI-5920 which isn't going to get fixed as they plan on replacing the current macros with scalameta (as far as I understand).

**Comment by backuitist** [comment]
There you go: https://github.com/backuity/clist#default-option-value

Feel free to re-open if that's still unclear.
